### ISSUE TITLE
PHP Fatal error while enabling tripal_jbrowse_api

### ISSUE THREAD

**Issue by ehsueh** [isubit/tripal_jbrowse_api#5]
Hi Nick,
 
Thank you for making the JBrowse module available for Tripal. :D

I'm currently encountering the following error when I try to enable the module:
> [20-Jan-2017 16:42:09 UTC] PHP Fatal error:  Only variables can be passed by reference in /var/www/html/sites/all/modules/tripal_jbrowse_api/tripal_jbrowse_api.module on line 226
Drush command terminated abnormally due to an unrecoverable error.                             [error]
Error: Only variables can be passed by reference in
/var/www/html/sites/all/modules/tripal_jbrowse_api/tripal_jbrowse_api.module, line 226
A non well formed numeric value encountered drush.inc:1643      

My commands were:
`git clone https://github.com/isubit/tripal_jbrowse_api.git tripal_jbwrowse_api`
`cd tripal_jbrowse_api`
`drush pm-enable tripal_jbrowse_api` 

Do you know what might be causing the error? 

Thanks,
Emma

**Comment by njbooher** [comment]
Could you tell me which version of PHP and which version of Drush you are using?

**Comment by ehsueh** [comment]
I'm using PHP 7.1.0 and Drush 7.4.0

**Comment by njbooher** [comment]
https://github.com/isubit/tripal_jbrowse_api/commit/aadc2d1dd61d53f90171cd76c24dd6eae14be2b7

That commit should have fixed this. Please try now.

**Comment by ehsueh** [comment]
Yes! It's working now. Thank you :smile:
